# Generated by Django 4.0.3 on 2022-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollnum', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=70)),
            ],
        ),
    ]
