# Generated by Django 4.0.3 on 2022-03-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='branche',
            new_name='branch',
        ),
    ]
